# Generated by Django 3.2.5 on 2021-07-27 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 17, 0, 51, 440474)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 17, 0, 51, 440438)),
        ),
    ]
