# Generated by Django 3.2.5 on 2021-07-27 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210727_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 21, 33, 23, 973373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 21, 33, 23, 973401, tzinfo=utc)),
        ),
    ]
