# Generated by Django 3.2.5 on 2021-07-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210728_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 12, 16, 59, 971894)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 12, 16, 59, 971915)),
        ),
    ]
