# Generated by Django 3.2.5 on 2021-07-27 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 21, 8, 31, 92974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='body',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='publications', to='publications.Like'),
        ),
    ]
