# Generated by Django 3.2.5 on 2021-07-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_like_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 12, 16, 59, 974197)),
        ),
    ]
