# Generated by Django 3.2.5 on 2021-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_alter_like_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
